theme: jekyll-theme-minimal
logo: https://fsmedia.imgix.net/19/0c/cb/40/f1bd/4826/baf9/75367d2c071e/luffy-wanted-poster.jpeg?rect=0%2C178%2C564%2C282&auto=format%2Ccompress&dpr=2&w=564
title: Bioinformatics
