---
title: "Class 7 R function and packages"
author: "Pin-Chung (Tony) Cheng"
date: "10/23/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("http://tinyurl.com/rescale-R")
```

Try rescle function again

```{r}
rescale(1:10)
```

```{r}
rescale(c(3,10,NA,7, "tony"))
```


```{r}
rescale2(c(3,10,NA,7, "tony"))
```
```{r}
both_na4 = function(x, y) {
  if (length(x) != length(y)) {
    stop("The two vectors are not the same length!!!")
    }
  sum( is.na(x) & is.na(y) )
}
```

```{r}
x <- c(NA, NA, NA)
y1 <- c( 1, NA, NA)
y2 <- c( 1, NA, NA, NA)

both_na4(x, y2)

```

```{r}
a = "tony cheng12345 hello"
sub("cheng)", "\\1", a)
```
```{r}
a = c(100, 100, 100, 100, 100, 90)
r = which.min(a)

a[-r]
```


```{r}

grade = function(x) {
  
  x_minus_one = x[-which.min(x)]
  sum(x_minus_one, na.rm= TRUE) / length(x_minus_one)
  
}
```

```{r}
# student 1
s1 = c(100, 100, 100, 100, 100, 100, 100, 90)
# student 2
s2 = c(100, NA, 90, 90, 90, 90, 97, 80)
```

```{r}
grade(s1)
grade(s2)
```
```{r}
install.packages(rmarkdown)
```

